### ISSUE TITLE
Rimozione scritta nelle società

### ISSUE THREAD

**Issue by DanielJamesTronca** [mrampazz/website-jd#10]
Poi Domenico mi ha chiesto che su tutti i clienti Punto ottico non venga scritto il nome della società ma solo Punto Ottico Humaneyes e l’indirizzo + num tel + mail.

Quindi da modificare:

- Dr snc – San Bonifacio
- Tre snc  - Vicenza
- Quattro snc – Verona
- Punto Ottico di Concato Domenico – Alte 
- Punto Ottico di Concato Domenico – Brescia
- PO usa corporation – Madison
- PO usa corporation - Brooklyn

Su tutti questi il nome da scrivere è Punto Ottico Humaneyes.

**Comment by mrampazz** [comment]
le ultime due USA non ci sono nelle sheet

**Comment by mrampazz** [comment]
gli altri sono fatti
