### ISSUE TITLE
Aggiunta occhiali

### ISSUE THREAD

**Issue by DanielJamesTronca** [mrampazz/website-jd#12]
Da aggiungere pagina ‘’acetate’’

- [x] Trinidad
- [x] Certosa
- [x] San lazzaro
- [ ] Ile madame
- [ ] Itouroup
- [ ] Shodoshima
- [ ] Sakhaline
- [ ] Naoshima
- [ ] Okinawa
- [ ] Yoron

 
Da **aggiungere** parina ‘’sunshine’’:

- [ ] Bd. Patch
- [ ] Fontanette
- [ ] Ch. Des amoureux
- [ ] Tour portalet
- [ ] Bd des jasmins

Aggiungere anche tutti i colori mancanti di tutti i modelli. Allego catalogo.
 
Allego tabelle con i nomi dei clienti per la mappa. (NON SO CHE DIAVOLO SIA, sto riportando i messaggi)

[JD_catalogo_settembre2020.pdf](https://github.com/mrampazz/website-jd/files/5432585/JD_catalogo_settembre2020.pdf)

**Comment by mrampazz** [comment]
e le foto?

**Comment by DanielJamesTronca** [comment]
> e le foto?

Deve mandarmele ancora hahaa da 3 giorni
