### ISSUE TITLE
Piccoli fix UI

### ISSUE THREAD

**Issue by DanielJamesTronca** [mrampazz/website-jd#8]
- [x] Oscurare sezione Limited (Commentiamola che sia mai che esca ancora)
- [x] Spostare le icone di instagram e facebook sotto il menu (al posto che sotto la foto)
- [ ] Voleva aggiungere slider in homepage ma non mi ha detto niente ed eviterei.

**Comment by mrampazz** [comment]
@DanielJamesTronca controlla icone insta + facebook
